config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/dogs'
  get 'welcome/lists'
  get 'welcome/users'
  get 'welcome/new'

  resources :users
  resources :lists
  resources :dogs

  root to: 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :list
  belongs_to :user

  validates_presence_of :list
  validates_presence_of :user
  validates :image, presence: true
  validates :breed, presence: true
  validates :color, presence: true
  validates :size,  presence: true
  validates :location, presence: true
  validates :date, presence: true
  # validates_format_of :date, :with => /(0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])[- \/.](19|20)\d\d/i, :message => "must be in the following format: mm/dd/yyyy"
  validates :description, presence: true

  mount_uploader :image, ImageUploader

  validates_processing_of :image
  validate :image_size_validation


  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/models/list.rb
class List < ApplicationRecord
  has_many :dog

  validates :status, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dog

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :phone, numericality: { only_integer: true }
 validates :phone, length: { is: 10}
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def full_name
   "#{first_name} #{last_name}"
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:image, :breed, :color, :size, :location, :date, :description, :list_id, :user_id, :remove_image)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to dogs_path
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:status)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to lists_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :phone, :email)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to lists_path
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def dogs
  end

  def lists
  end

  def users
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dogs/_form.html.erb
<%= form_for @dog, html: { multipart: true } do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% @dog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div >
    <%= f.label :image %>:
    <%= f.file_field :image %>
  </div>

  <div >
    <% if f.object.image? %>
      <%= image_tag f.object.image.small.url %>
      <%= f.label :remove_image %>:
      <%= f.check_box :remove_image %>
    <% end %>
  </div>

  <div>
      <%= f.label :list_id %>:
      <%= f.collection_radio_buttons :list_id, List.all, :id, :status %>
  </div>

  <div>
    <%= f.label :breed %>:
    <%= f.text_field :breed %>
  </div>

  <div>
    <%= f.label :color %>:
    <%= f.text_field :color %>
  </div>

  <div>
      <%= f.label :size %>:
      <%= f.radio_button :size, 'Small' %> Small
      <%= f.radio_button :size, 'Medium' %> Medium
      <%= f.radio_button :size, 'Large' %> Large
  </div>

  <div>
      <%= f.label :location %>:
      <%= f.select(:location, options_for_select([["North Durham", "North Durham"], ["Downtown Durham", "Downtown Durham"], ["South Durham", "South Durham"], ["East Durham", "East Durham"], ["West Durham", "West Durham"]]), include_blank: true) %>
  </div>

  <div>
    <%= f.label :date %>:
    <%= f.date_select :date %>
  </div>

  <div>
    <%= f.label :description %>:
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :full_name, include_blank: true %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/dogs/edit.html.erb
<!DOCTYPE html>
<html>

  <body>
    <h1>Editing Dog</h1>
    
    <%= render "form", dog: @dog %>

    <span><%= link_to 'Back', dogs_path %></span>

  </body>

</html>



<!-- <h1>Editing Dog</h1>
<#%= render 'form', dog: @dog %>
<#%= link_to 'Show', @dog %> |
<#%= link_to 'Back', dogs_path %> -->

app/views/dogs/index.html.erb
<!DOCTYPE html>
<html>

  <body>
    <p id="notice"><%= notice %></p>

    <div>
      <h1>List of All the Dogs Missing</h1>
    </div>

    <span><%= link_to 'Add New Dog', new_dog_path %></span>

    <div>
       <% @dogs.each do |dog| %>
         <% if dog.image? %>
           <p><%= image_tag dog.image.small.url%></p>
         <% end %>
         <p>Dog ID: <%= dog.id %></p>
         <p>Status: <%= dog.list.status %></p>
         <p> Breed: <%= dog.breed %></p>
         <p> Color: <%= dog.color %></p>
         <p> Size: <%= dog.size %></p>
         <p> Location: <%= dog.location %></p>
         <p> Date: <%= dog.date.strftime("%m/%d/%Y") %></p>
         <p> Description: <%= dog.description %></p>

         <span><%= link_to 'Show', dog %></span>
         <span><%= link_to 'Edit', edit_dog_path(dog) %></span>
         <span><%= link_to 'Delete', dog, method: :delete, data: { confirm: 'Are you sure?' } %></span>

       <% end %>
     </div>

     <span><%= link_to 'Add New Dog', new_dog_path %></span>

   </body>
</html>


<!-- ---------------------------------------------------------------------------------------------------------------------------- -->


<!-- <p id="notice"><#%= notice %></p> -->
<!--
<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Breed</th>
      <th>Color</th>
      <th>Size</th>
      <th>Location</th>
      <th>Date</th>
      <th>Description</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% @dogs.each do |dog| %>
      <tr>
        <td><#%= dog.image %></td>
        <td><#%= dog.breed %></td>
        <td><#%= dog.color %></td>
        <td><#%= dog.size %></td>
        <td><#%= dog.location %></td>
        <td><#%= dog.date %></td>
        <td><#%= dog.description %></td>
        <td><#%= dog.list %></td>
        <td><#%= dog.user %></td>
        <td><#%= link_to 'Show', dog %></td>
        <td><#%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><#%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<#%= link_to 'New Dog', new_dog_path %> -->

app/views/dogs/new.html.erb
<!DOCTYPE html>
<html>

  <body>
    <h1>New Dog</h1>
    
    <%= render "form", dog: @dog %>

    <span><%= link_to 'Back', dogs_path %></span>

  </body>

</html>


<!-- <h1>New Dog</h1>
<#%= render 'form', dog: @dog %>
<#%= link_to 'Back', dogs_path %> -->

app/views/dogs/show.html.erb
<!DOCTYPE html>
<html>

  <body>
    <p id="notice"><%= notice %></p>

    <div>
      <% if @dog.image? %>
        <p><%= image_tag @dog.image.small.url %></p>
      <% end %>
      <p><span>Dog ID:</span> <%= @dog.id %></p>
      <p><span>Status:</span> <%= @dog.list.status %></p>
      <p><span>Breed:</span> <%= @dog.breed %></p>
      <p><span>Color:</span> <%= @dog.color %></p>
      <p><span>Size:</span> <%= @dog.size %></p>
      <p><span>Location:</span> <%= @dog.location %></p>
      <p><span>Date:</span> <%= @dog.date.strftime("%m/%d/%Y") %></p>
      <p><span>Description:</span> <%= @dog.description %></p>
      <p><span>First Name:</span> <%= @dog.user.first_name %></p>
      <p><span>Last Name:</span> <%= @dog.user.last_name %></p>
      <p><span>Phone Number:</span> <%= @dog.user.phone %></p>
      <p><span>Email:</span> <%= @dog.user.email %></p>
    </div>


    <div>
    <span><%= link_to 'Edit', edit_dog_path(@dog) %></span>
    <span><%= link_to 'Back', dogs_path %></span>
    <span><%= link_to 'Delete', @dog, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    <span><%= link_to 'Back To List', lists_path %></span>
    </div>
  </body>

</html>









<!-- ------------------------------------------------------------------------------------------
<p id="notice"><#%= notice %></p>

<p>
  <strong>Image:</strong>
  <#%= @dog.image %>
</p>

<p>
  <strong>Breed:</strong>
  <#%= @dog.breed %>
</p>

<p>
  <strong>Color:</strong>
  <#%= @dog.color %>
</p>

<p>
  <strong>Size:</strong>
  <#%= @dog.size %>
</p>

<p>
  <strong>Location:</strong>
  <#%= @dog.location %>
</p>

<p>
  <strong>Date:</strong>
  <#%= @dog.date %>
</p>

<p>
  <strong>Description:</strong>
  <#%= @dog.description %>
</p>

<p>
  <strong>List:</strong>
  <#%= @dog.list %>
</p>

<p>
  <strong>User:</strong>
  <#%= @dog.user %>
</p>

<#%= link_to 'Edit', edit_dog_path(@dog) %> |
<#%= link_to 'Back', dogs_path %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= link_to "Home", root_path%>
    <%= link_to "Dogs", dogs_path%>
    <%= link_to "Lists", lists_path%>
    <%= link_to "Users", users_path%>
    <%= link_to "New Entry", welcome_new_path%>
    <a href="mailto:cindy.mendes@hotmail.fr">Report a Bug</a>


    <%= yield %>



  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>

  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/lists/edit.html.erb
<!DOCTYPE html>
<html>

  <body>
    <h1>Editing List</h1>
    
    <%= render "form", list: @list %>

    <span><%= link_to 'Back', lists_path %></span>

  </body>

</html>






<!-- <h1>Editing List</h1>
<#%= render 'form', list: @list %>
<#%= link_to 'Show', @list %> |
<#%= link_to 'Back', lists_path %> -->

app/views/lists/index.html.erb
<!DOCTYPE html>
<html>

  <body>

    <p id="notice"><%= notice %></p>

    <div>
      <div>
        <h1>LISTS</h1>
      </div>

      <div>
        <% @lists.each do |list| %>
          <p><%= list.status %> List <span><%= link_to 'Show', list %></span></p>
        <% end %>
      </div>

      <!-- <#%= link_to 'New List', new_list_path %>  -->

      <div>
        <p>Website by Cindy Mendes</p>
      </div>

    </div>

     </body>
</html>








<!-- ------------------------------------------------------------------------------------------
<p id="notice"><#%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% @lists.each do |list| %>
      <tr>
        <td><#%= list.status %></td>
        <td><#%= link_to 'Show', list %></td>
        <td><#%= link_to 'Edit', edit_list_path(list) %></td>
        <td><#%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<#%= link_to 'New List', new_list_path %> -->

app/views/lists/new.html.erb
<!DOCTYPE html>
<html>

  <body>
    <h1>New List</h1>
    
    <%= render "form", list: @list %>

    <span><%= link_to 'Back', lists_path %></span>

  </body>

</html>




<!-- <h1>New List</h1>
<#%= render 'form', list: @list %>
<#%= link_to 'Back', lists_path %> -->

app/views/lists/show.html.erb
<!DOCTYPE html>
<html>

  <body>

    <h1><%= @list.status %> List</h1>

    <p> Status: <%= @list.status %></p>


    <% @list.dog.each do |list| %>


      <% if list.image? %>
        <p>Image: <%= image_tag list.image.small.url %></p>
      <% end %>

      <p> Dog ID: <%= list.id %></p>
      <p> Breed: <%= list.breed %></p>
      <p> Color: <%= list.color %></p>
      <p> Size: <%= list.size %></p>
      <p> Location: <%= list.location %></p>
      <p> Date: <%= list.date.strftime("%m/%d/%Y") %></p>
      <p> Description: <%= list.description %></p>

      <%= link_to 'Show Dog', list %> |
      <%= link_to 'Edit Dog', edit_dog_path(list) %> |
      <%= link_to 'Destroy Dog', list, method: :delete, data: { confirm: 'Are you sure?' } %>

    <% end %>


    <span><%= link_to 'Edit', edit_list_path(@list) %></span> |
    <span><%= link_to 'Back To List', lists_path %></span>
    <span><%= link_to 'Destroy', @list, method: :delete, data: { confirm: 'Are you sure?' } %></span>

    <div>
      <p>Website by Cindy Mendes</p>
    </div>
  </body>

</html>











<!-- <p id="notice"><#%= notice %></p>

<p>
  <strong>Status:</strong>
  <#%= @list.status %>
</p>

<#%= link_to 'Edit', edit_list_path(@list) %> |
<#%= link_to 'Back', lists_path %> -->

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>

  <body>
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <span><%= link_to 'Back', users_path %></span>

  </body>

</html>







<!--
<h1>Editing User</h1>

<#%= render 'form', user: @user %>

<#%= link_to 'Show', @user %> |
<#%= link_to 'Back', users_path %> -->

app/views/users/index.html.erb
<!DOCTYPE html>
<html>

  <body>
    <p id="notice"><%= notice %></p>

    <div>
      <h1>Users</h1>
    </div>

    <div>
       <% @users.each do |user| %>
        <p>First Name: <%= user.first_name %></p>
        <p>Last Name: <%= user.last_name %></p>
        <p>Phone Number: <%= user.phone %></p>
        <p>Email: <%= user.email %></p>
        <span><%= link_to 'Show', user %></span>
        <span><%= link_to 'Edit', edit_user_path(user) %></span>
        <span><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></span>

       <% end %>
     </div>

     <span><%= link_to 'New User', new_user_path %></span>

   </body>
</html>







<!-- ---------------------------------------------------------------------------------------------------------------------------- -->


<!-- <p id="notice"><#%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% @users.each do |user| %>
      <tr>
        <td><#%= user.first_name %></td>
        <td><#%= user.last_name %></td>
        <td><#%= user.phone %></td>
        <td><#%= user.email %></td>
        <td><#%= link_to 'Show', user %></td>
        <td><#%= link_to 'Edit', edit_user_path(user) %></td>
        <td><#%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<#%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<!DOCTYPE html>
<html>

  <body>
    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <span><%= link_to 'Back', users_path %></span>

  </body>

</html>





<!-- <h1>New User</h1>
<#%= render 'form', user: @user %>
<#%= link_to 'Back', users_path %> -->

app/views/users/show.html.erb
<!DOCTYPE html>
<html>

  <body>
    <p id="notice"><%= notice %></p>

    <div>
      <p><span>First Name:</span> <%= @user.first_name %></p>
      <p><span>Last Name:</span> <%= @user.last_name %></p>
      <p><span>Phone Number:</span> <%= @user.phone %></p>
      <p><span>Email:</span> <%= @user.email %></p>

      <% @user.dog.each do |dog| %>
        <p><span>Dog ID:</span> <%= dog.id %></p>
        <span><%= link_to 'Show Dog', dog %></span>
        <span><%= link_to 'Edit Dog', edit_dog_path(dog) %></span>
        <span><%= link_to 'Destroy Dog', dog, method: :delete, data: { confirm: 'Are you sure?' } %></span>

      <% end %>
    </div>


    <div>
      <span><%= link_to 'Edit', edit_user_path(@user) %></span>
      <span><%= link_to 'Back', users_path %></span>
    </div>

  </body>

</html>






<!--
<p id="notice"><#%= notice %></p>

<p>
  <strong>First name:</strong>
  <#%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <#%= @user.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <#%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <#%= @user.email %>
</p>

<#%= link_to 'Edit', edit_user_path(@user) %> |
<#%= link_to 'Back', users_path %> -->

app/views/welcome/dogs.html.erb
<h1>Welcome#dogs</h1>
<p>Find me in app/views/welcome/dogs.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/lists.html.erb
<h1>Welcome#lists</h1>
<p>Find me in app/views/welcome/lists.html.erb</p>

app/views/welcome/new.html.erb
<h1>Welcome#new</h1>
<p>Find me in app/views/welcome/new.html.erb</p>

app/views/welcome/users.html.erb
<h1>Welcome#users</h1>
<p>Find me in app/views/welcome/users.html.erb</p>